import { roleId } from "./roleId";

export const sidebarMenu = [
  {
    name: "home",
    display_name: "Inicio",
    tranlation_key: "menu.home",
    path: "/dashboard",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Clientes",
    tranlation_key: "menu.clients",
    path: "/clients",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Facturación",
    tranlation_key: "menu.invoicing",
    path: "/invoicing",
    roles: [roleId.ROOT, roleId.USER],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Arreglos de Pago",
    tranlation_key: "menu.arrangement",
    path: "/arrangement",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Procesos de corte",
    tranlation_key: "menu.cutting",
    path: "/courts",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Lista de pagos",
    tranlation_key: "menu.payments",
    path: "/payment",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "debtors",
    display_name: "Deudores",
    tranlation_key: "menu.debtors",
    path: "/debtors",
    roles: [roleId.ROOT, roleId.USER],
    submodules: [],
  },
  {
    name: "formats",
    display_name: "Formatos",
    tranlation_key: "menu.formats",
    path: "/formats",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "clients",
    display_name: "Moderadores",
    tranlation_key: "menu.moderators",
    path: "/moderators",
    roles: [roleId.ROOT],
    submodules: [],
  },
  {
    name: "settings",
    display_name: "Perfil",
    tranlation_key: "menu.profile",
    path: "/profile",
    roles: [roleId.USER, roleId.MODERATOR],
    submodules: [],
  },
  {
    name: "settings",
    display_name: "Configuracion",
    tranlation_key: "menu.settings",
    path: "/settings",
    roles: [roleId.ROOT],
    submodules: [],
  },
];
